//
//  MarvelDataViewController.swift
//  Marvel
//
//  Created by Mariano Quiroga on 8/6/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MarvelDataDisplayLogic: AnyObject {

}

class MarvelDataViewController: UIViewController {

  // MARK: - Properties - Dependencies

  var interactor: MarvelDataBusinessLogic?
  var router: (MarvelDataRoutingLogic & MarvelDataDataPassing)?

  // MARK: - Properties - Internal

  let sceneView = MarvelDataView()

  // MARK: Object lifecycle

  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }

  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }

  // MARK: Properties

  let testLabel = UILabel()

  // MARK: Setup

  private func setup() {
    let viewController = self
    let interactor = MarvelDataInteractor()
    let presenter = MarvelDataPresenter()
    let router = MarvelDataRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }

  // MARK: View lifecycle

  override func viewDidLoad() {
    super.viewDidLoad()
    view.backgroundColor = .green
  }
}

extension MarvelDataViewController: MarvelDataDisplayLogic {

}
