//
//  MarvelDataModels.swift
//  Marvel
//
//  Created by Mariano Quiroga on 8/6/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MarvelData {
  // MARK: - Use cases

  enum Characters {
    struct Request {

    }
    struct Response {
      let state: LoadMarvelDataViewState
    }
    struct ViewModel {
      let action: LoadMarvelDataViewAction
    }
  }
}

// MARK: - Business models

enum LoadMarvelDataViewState {
  case error
  case success(charactersResult: [CharacterResult])
}

// MARK: - View models

enum LoadMarvelDataViewAction {
  case showData(characters: [CharactersCellViewData])
  case showError(message: String)
}
