//
//  MarvelDataPresenter.swift
//  Marvel
//
//  Created by Mariano Quiroga on 8/6/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MarvelDataPresentationLogic {

}

class MarvelDataPresenter: MarvelDataPresentationLogic {

  weak var viewController: MarvelDataDisplayLogic?
  
  // MARK: Do something
  

}
